### ISSUE TITLE
Position:Absolute not being proccesed

### ISSUE THREAD

**Issue by DanielZambranoC** [tsayen/dom-to-image#147]
Trying to print a result from JqueryOrgChart

![domtoimg](https://user-images.githubusercontent.com/28786672/29074708-450ad444-7c1e-11e7-8e2d-dd0bbb03a67f.png)

Even better than html2canvas, but position absolute not being interpreted

**Comment by shamahoque** [comment]
I ran into a similar problem with the position:absolute elements not being rendered accurately in the image. 

Explicitly declaring position:relative on the outer/parent element solved the problem for me.

Example:
```css
.outer {
    position: relative;
}
.inner {
    position: absolute;
}
```
```html
<div class="outer">
  <div class="inner">...</div>
  <div class="inner">...</div>
</div>
```
